SELECT UFORIG, UFDEST,
       TIPRESTRICAO, CODRESTRICAO, TIPRESTRICAO2, CODRESTRICAO2,
       CODTRIB, ALIQUOTA, ALIQINTDEST, ALIQUFDEST, REDBASE, PERCICMSFCP,
       DTINICIOVIGENCIA, DTFIMVIGENCIA
FROM METALPRD.TGFICM
WHERE UFORIG = 13
  AND UFDEST IN (5,8,10,13,15,17,19,21,25)
  AND ( (TIPRESTRICAO2 = 'I' AND CODRESTRICAO2 IN (0,122,311))
     OR (TIPRESTRICAO  = 'I' AND CODRESTRICAO  IN (0,122,311))
     OR (TIPRESTRICAO = 'N' AND TIPRESTRICAO2 = 'N')
     OR (TIPRESTRICAO = 'S' OR TIPRESTRICAO2 = 'S') )
ORDER BY UFDEST, CODRESTRICAO2, TIPRESTRICAO, TIPRESTRICAO2
