SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'METALPRD'
  AND TABLE_NAME IN ('TGFITE','TGFCAB')
  AND (COLUMN_NAME LIKE '%ICMS%' OR COLUMN_NAME LIKE '%DIFAL%'
       OR COLUMN_NAME LIKE '%FCP%' OR COLUMN_NAME LIKE '%PARTILHA%')
ORDER BY TABLE_NAME, COLUMN_NAME
