SELECT c.NUNOTA, c.NUMNOTA, TO_CHAR(c.DTNEG,'YYYY-MM-DD') AS DTNEG, c.CODTIPOPER AS TOP,
       c.CLASSIFICMS, u.UF AS UFDEST,
       i.CODPROD, i.QTDNEG, i.VLRTOT,
       i.BASEICMS, i.ALIQICMS, i.VLRICMS, i.VLRICMSUFDEST,
       c.VLRICMSFCP, c.VLRICMSDIFALDEST
FROM METALPRD.TGFCAB c
JOIN METALPRD.TGFITE i ON i.NUNOTA = c.NUNOTA
JOIN METALPRD.TGFPAR p ON p.CODPARC = c.CODPARC
JOIN METALPRD.TSICID d ON d.CODCID = p.CODCID
JOIN METALPRD.TSIUFS u ON u.CODUF = d.UF
WHERE i.CODPROD IN (15956,20303,20322,22467,39563,39587,41912,42194)
  AND c.CODTIPOPER IN (306,313)
  AND c.DTNEG >= DATE '2025-08-01'
ORDER BY i.CODPROD, u.UF, c.DTNEG
