SELECT UF, MES, ALIQ_INTER, PCT_DIFAL, PCT_FCP, COUNT(*) AS NOTAS,
       MIN(DIA) AS PRIMEIRA, MAX(DIA) AS ULTIMA
FROM (
    SELECT u.UF,
           TO_CHAR(c.DTNEG,'YYYY-MM')                            AS MES,
           TO_CHAR(c.DTNEG,'YYYY-MM-DD')                         AS DIA,
           ROUND(i.ALIQICMS, 2)                                  AS ALIQ_INTER,
           ROUND(c.VLRICMSDIFALDEST * 100 / i.BASEICMS, 2)       AS PCT_DIFAL,
           ROUND(c.VLRICMSFCP * 100 / i.BASEICMS, 2)             AS PCT_FCP
    FROM METALPRD.TGFCAB c
    JOIN METALPRD.TGFITE i ON i.NUNOTA = c.NUNOTA
    JOIN METALPRD.TGFPAR p ON p.CODPARC = c.CODPARC
    JOIN METALPRD.TSICID d ON d.CODCID = p.CODCID
    JOIN METALPRD.TSIUFS u ON u.CODUF = d.UF
    WHERE c.CODTIPOPER = 306
      AND c.CLASSIFICMS = 'C'
      AND u.UF IN ('RJ','PR','RS')
      AND c.DTNEG >= DATE '2025-08-01'
      AND i.BASEICMS > 0
      AND (SELECT COUNT(*) FROM METALPRD.TGFITE x WHERE x.NUNOTA = c.NUNOTA) = 1
)
GROUP BY UF, MES, ALIQ_INTER, PCT_DIFAL, PCT_FCP
ORDER BY UF, MES, PCT_DIFAL
