SELECT c.NUNOTA, TO_CHAR(c.DTNEG,'YYYY-MM-DD') AS DIA, i.CODPROD, i.VLRTOT,
       c.BASEPIS, c.VLRPIS, c.VLRCOFINS,
       ROUND((c.VLRPIS + c.VLRCOFINS) * 100 / NULLIF(i.VLRTOT,0), 4) AS PCT_S_TOTAL,
       ROUND((c.VLRPIS + c.VLRCOFINS) * 100 / NULLIF(c.BASEPIS,0), 4) AS PCT_S_BASE,
       ROUND(c.BASEPIS * 100 / NULLIF(i.VLRTOT,0), 2)                 AS BASE_PCT_TOTAL
FROM METALPRD.TGFCAB c
JOIN METALPRD.TGFITE i ON i.NUNOTA = c.NUNOTA
WHERE c.CODTIPOPER = 306
  AND c.CLASSIFICMS = 'C'
  AND c.DTNEG >= DATE '2026-06-01'
  AND i.CODPROD IN (15956,22467,39563,39587,41912,42194)
  AND (SELECT COUNT(*) FROM METALPRD.TGFITE x WHERE x.NUNOTA = c.NUNOTA) = 1
ORDER BY c.DTNEG, i.CODPROD
