SELECT TABLE_NAME, COLUMN_NAME
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'METALPRD'
  AND TABLE_NAME IN ('TGFITE','TGFCAB')
  AND (COLUMN_NAME LIKE '%PIS%' OR COLUMN_NAME LIKE '%COFINS%')
ORDER BY TABLE_NAME, COLUMN_NAME
