SELECT c.CODTIPOPER,
       COUNT(*)                                          AS NOTAS,
       COUNT(c.BASEPIS)                                  AS COM_BASEPIS,
       COUNT(c.VLRPIS)                                   AS COM_VLRPIS,
       ROUND(AVG(c.VLRPIS * 100 / NULLIF(c.BASEPIS,0)),4)    AS PCT_PIS_MEDIO,
       ROUND(AVG(c.VLRCOFINS * 100 / NULLIF(c.BASEPIS,0)),4) AS PCT_COFINS_MEDIO,
       ROUND(AVG(c.BASEPIS * 100 / NULLIF(c.VLRNOTA,0)),2)   AS BASE_PCT_NOTA
FROM METALPRD.TGFCAB c
WHERE c.DTNEG >= DATE '2026-01-01'
GROUP BY c.CODTIPOPER
HAVING COUNT(c.VLRPIS) > 0
ORDER BY COUNT(c.VLRPIS) DESC
FETCH FIRST 15 ROWS ONLY
