WITH v AS (
  SELECT d.CODPROD, d.TIPIMPOSTO, d.VLRUNITMED, d.DTMOV,
         ROW_NUMBER() OVER (PARTITION BY d.CODPROD, d.TIPIMPOSTO
                            ORDER BY d.DTMOV DESC) AS RN
  FROM METALPRD.TGFEFDVMRSTDIA d
  WHERE d.CODEMP = 1
    AND d.CODPROD IN (15956, 20303, 20322, 22467, 39563, 39587, 41912, 42194)
    AND d.TIPIMPOSTO IN ('S', 'I')
    AND d.DTMOV <= SYSDATE
    AND NVL(d.VLRUNITMED, 0) <> 0
)
SELECT CODPROD,
       ROUND(MAX(CASE WHEN TIPIMPOSTO = 'S' THEN VLRUNITMED END), 4) AS S_ST,
       ROUND(MAX(CASE WHEN TIPIMPOSTO = 'I' THEN VLRUNITMED END), 4) AS I_ICMS,
       TO_CHAR(MAX(DTMOV), 'YYYY-MM-DD')                             AS DTMOV
FROM v
WHERE RN = 1
GROUP BY CODPROD
ORDER BY CODPROD
